export const routesConstants = {
  welcome: 'Welcome',
  login: 'Login',
  bottomTab: 'BottomTab',
  signUp: 'SignUp',
  verifyOtp: 'VerifyOtp',
  forgotPassword: 'ForgotPassword',
  welcomeFirstRun: 'WelcomeFirstRun',
  songs: 'Songs',
  record: 'Record',
  create: 'Create',
  library: 'Library',
  myAccount: 'MyAccount',
  jobs: 'Jobs',
  newJob: 'NewJob',
  colours: 'Colours',
  profile: 'Profile',
  addressSearch: 'AddressSearch',
  measurementReview: 'MeasurementReview',
  quoteDetails: 'QuoteDetails',
  jobDetail: 'JobDetail',
  quotesList: 'QuotesList',
  photosList: 'PhotosList',
  notesList: 'NotesList',
  deliveryRequest: 'DeliveryRequest',
  deliverySuccess: 'DeliverySuccess',
  deliveryDetail: 'DeliveryDetail',
  compareColours: 'CompareColours',
  paintAndColour: 'PaintAndColour',

  measuring: 'Measuring',
  adjustOutline: 'AdjustOutline',
  tryOnRoof: 'TryOnRoof',
  quoteSaved: 'QuoteSaved',
  manualMeasurement: 'ManualMeasurement',
  chooseTile: 'ChooseTile',
  tileDetails: 'TileDetails',
  businessDetails: 'BusinessDetails',
  accountBusinessDetails: 'AccountBusinessDetails',
  deleteAccount: 'DeleteAccount',
  measurementDetail: 'MeasurementDetail',
  existingRoof: 'ExistingRoof',
  changePassword: 'ChangePassword',
  privacyPolicy: 'PrivacyPolicy',
  termsOfUse: 'TermsOfUse',
} as const;


export type RouteConstantsType = typeof routesConstants;
