export const apiEndPoint = {
signup:'auth/sign-up/email',
socialLogin:"auth/sign-in/social",
login:'auth/sign-in/email',
sendOtp:"auth/otp/send",
verifyEmail:"auth/verify-email",
verifyForgotOtp:"auth/password/forget/verify",
forgotPassword:'auth/password/forget',
resetPassword:"auth/password/reset",
changePassword:"auth/password/change",
getProfile:"auth/me",
getBusinessDetails:"auth/business-details",
updateBusinessDetails:'auth/me/business',
getTiles:"tiles",
getTileProfiles: 'tiles',
getTileColors: 'tiles/colors',
getJobs:"jobs",
getJobDetail:"jobs/details",
calculateMaterial:"jobs/calculateMaterial",
createJob:"jobs/create",
getJobQuotes:"quotes",
getSingleJobQuoteDetail:"quotes/single",
requestDelivery: "deliveries",
deleteAccount:"auth/delete/me"
};
