const countryCodes = [
  {code: '+1', country: 'United States'},
  {code: '+44', country: 'United Kingdom'},
  {code: '+91', country: 'India'},
  {code: '+81', country: 'Japan'},
  {code: '+49', country: 'Germany'},
  {code: '+61', country: 'Australia'},
  {code: '+86', country: 'China'},
  {code: '+33', country: 'France'},
  {code: '+55', country: 'Brazil'},
  {code: '+39', country: 'Italy'},
  {code: '+7', country: 'Russia'},
  {code: '+34', country: 'Spain'},
  {code: '+82', country: 'South Korea'},
  {code: '+971', country: 'United Arab Emirates'},
  {code: '+63', country: 'Philippines'},
  {code: '+52', country: 'Mexico'},
  {code: '+62', country: 'Indonesia'},
  {code: '+27', country: 'South Africa'},
  {code: '+65', country: 'Singapore'},
  {code: '+41', country: 'Switzerland'},
  {code: '+46', country: 'Sweden'},
  {code: '+47', country: 'Norway'},
  {code: '+90', country: 'Turkey'},
  {code: '+31', country: 'Netherlands'},
  {code: '+34', country: 'Spain'},
  {code: '+60', country: 'Malaysia'},
  {code: '+64', country: 'New Zealand'},
  {code: '+353', country: 'Ireland'},
  {code: '+351', country: 'Portugal'},
  {code: '+48', country: 'Poland'},
  {code: '+420', country: 'Czech Republic'},
  {code: '+30', country: 'Greece'},
  {code: '+43', country: 'Austria'},
  {code: '+32', country: 'Belgium'},
  {code: '+45', country: 'Denmark'},
  {code: '+358', country: 'Finland'},
  {code: '+36', country: 'Hungary'},
  {code: '+964', country: 'Iraq'},
  {code: '+353', country: 'Ireland'},
  {code: '+972', country: 'Israel'},
  {code: '+98', country: 'Iran'},
  {code: '+94', country: 'Sri Lanka'},
  {code: '+964', country: 'Iraq'},
  {code: '+54', country: 'Argentina'},
  {code: '+20', country: 'Egypt'},
  {code: '+966', country: 'Saudi Arabia'},
  {code: '+254', country: 'Kenya'},
  {code: '+258', country: 'Mozambique'},
  {code: '+233', country: 'Ghana'},
];

export default countryCodes;
